[package]
name                 = "ventana-backend-win32"
description          = "A cross-platform, iterator-based windowing library"
version              = "0.0.3"
readme.workspace     = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
log               = "0.4"
crossbeam-channel = "0.5"
crossbeam-queue   = "0.3"

[dependencies.ventana-hal]
version = "0.0.3"
path = "../ventana-hal"

[target.'cfg(target_os = "windows")'.dependencies]
win64 = "0.0.19"
