[package]
name                 = "ventana-backend-wayland"
description          = "A cross-platform, iterator-based windowing library"
version              = "0.0.3"
readme.workspace     = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
repository.workspace = true

[features]
default = []

[build-dependencies]
cfg_aliases = "0.2"

[dependencies]
log       = "0.4"
thiserror = "2.0"

bitflags = "2.9"
synchronize = "1.0"

# xkbcommon-dl = "0.4.2"
# xkbcommon = "0.9"

[dependencies.ventana-hal]
version = "0.0.4"
path = "../ventana-hal"

[target.'cfg(all(unix, not(any(target_os = "redox", target_family = "wasm", target_os = "android", target_vendor = "apple"))))'.dependencies]
wayland-client = { version = "0.31", features = ["system"] }
wayland-kbd = "0.13.1"
sctk = { package = "smithay-client-toolkit", version = "0.20", default-features = false, features = ["calloop"] }
