[package]
name                 = "ventana-backend-wayland"
description          = "A cross-platform, iterator-based windowing library"
version              = "0.0.1"
readme.workspace     = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
repository.workspace = true

[features]
default = []

[build-dependencies]
cfg_aliases = "0.2"

[dependencies]
log       = "0.4"
thiserror = "2.0"

bitflags = "2.9"
synchronize = "1.0"

# xkbcommon-dl = "0.4.2"
# xkbcommon = "0.9"

[dependencies.ventana-hal]
version = "0.0.3"
path = "../ventana-hal"

# not sure why, but sctk still tries to compile build scripts on other targets, so this guard is necessary to avoid erroneous warnings from rust-analyzer
[target.'cfg(all(unix, not(any(target_os = "redox", target_family = "wasm", target_os = "android", target_vendor = "apple"))))'.dependencies.sctk]
package = "smithay-client-toolkit"
default-features = false
version = "0.20.0"
