[package]
name = "window-input"
readme.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[features]
serde = ["dep:serde", "bitflags/serde"]

[dependencies]
serde = { version = "1.0.x", optional = true }
bitflags = "2.9.x"
smol_str = "0.3.x"