[package]
name    = "example"
version = "0.1.0"
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
log                = "0.4"
tracing            = { version = "0.1", features = ["log"] }
tracing-appender   = "0.2"
tracing-log        = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

anyhow     = "1.0"

wgpu        = "29.0"
pollster    = "0.4"

[dependencies.ventana]
version = "*"
path = "../ventana"
