[package]
name                 = "ventana-hal"
description          = "A cross-platform, iterator-based windowing library"
version              = "0.0.3"
readme.workspace     = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
repository.workspace = true

[features]
default = []
serde   = ["dep:serde"]

[dependencies]
log       = "0.4"
thiserror = "2.0"
serde     = { version = "1.0", optional = true }
bitflags  = "2.11"
smol_str  = "0.3"
strum     = { version = "0.28", features = ["derive"] }

# Window thread
crossbeam-channel = "0.5"
crossbeam-queue   = "0.3"

# Standard windowing types
dpi               = "0.1"
keyboard-types    = "0.8"
pointer-types     = "0.5"
rgb               = "0.8"
cursor-icon       = "1.2"
raw-window-handle = "0.6"
