[package]
name                 = "ventana-backend-x11"
description          = "A cross-platform, iterator-based windowing library"
version              = "0.0.2"
readme.workspace     = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
keywords.workspace   = true
categories.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
log = "0.4"

[dependencies.ventana-hal]
version = "0.0.3"
path = "../ventana-hal"

[target.'cfg(all(unix, not(any(target_os = "redox", target_family = "wasm", target_os = "android", target_vendor = "apple"))))'.dependencies]
x11rb = { version = "0.13", features = [
  "allow-unsafe-code",
  "raw-window-handle",
  "dl-libxcb",
  "cursor",
  "extra-traits",
  "randr",
  "resource_manager",
  "xinput",
  "xkb",
]}

[target.'cfg(not(all(unix, not(any(target_os = "redox", target_family = "wasm", target_os = "android", target_vendor = "apple")))))'.dependencies]
x11rb = { version = "0.13", features = [
  "allow-unsafe-code",
  "raw-window-handle",
  # "dl-libxcb",
  "cursor",
  "extra-traits",
  "randr",
  "resource_manager",
  "xinput",
  "xkb",
]}

